---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s-labs.github.io/helm-charts
      chart: app-template
      version: '>=5.0.0 <6.0.0'
      sourceRef:
        kind: HelmRepository
        name: bjw-s-labs
        namespace: flux-system
      interval: 5m0s
  values:
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: ghcr.io/esphome/esphome
              tag: "2026.5.3"
            env:
              TZ: "America/New_York"

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: 80
            targetPort: 6052
            protocol: TCP

    ingress:
      main:
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
        - host: esphome.leonmachado.com
          paths:
          - path: /
            service:
              identifier: main
              port: 80
        tls:
        - secretName: esphome-tls
          hosts:
          - esphome.leonmachado.com

    persistence:
      config:
        type: persistentVolumeClaim
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
        - path: /config
