---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openwebui
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: open-webui
      version: '>=5.0.0 <6.0.0'
      sourceRef:
        kind: HelmRepository
        name: openwebui-charts
        namespace: flux-system
      interval: 5m0s
  values:
    # image:
      # tag: git-6f4a863
    ollama:
      enabled: true
      ollama:
        models:
          pull: 
            # - hf.co/openbmb/MiniCPM-o-2_6-gguf:F16
            - hf.co/openbmb/MiniCPM-o-2_6-gguf:Q6_K
            # - Llava:7b
            # - llama3.2
            - mistral-nemo
          run:
            # - hf.co/openbmb/MiniCPM-o-2_6-gguf:F16
            - hf.co/openbmb/MiniCPM-o-2_6-gguf:Q6_K
            # - Llava:7b
            # - llama3.2
            # - mistral-nemo
    pipelines:
      enabled: false
    hostNetwork: true
    resources:
      requests:
        memory: 15Gi
        cpu: 10000m
      limits:
        memory: 20Gi
        cpu: 20000m
    ingress:
      enabled: true
      ingressClassName: nginx
      host: ai.leonmachado.com
    # persistentVolume:
    #   enabled: true
    #   storageClass: longhorn
    #   size: 30Gi
    