---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openwebui
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: open-webui
      version: '>=5.0.0 <6.0.0'
      sourceRef:
        kind: HelmRepository
        name: openwebui-charts
        namespace: flux-system
      interval: 5m0s
  values:
    # image:
      # tag: git-6f4a863
    ollama:
      enabled: true
      ollama:
        models:
          pull: 
            -  minicpm-v
            # - llama3.2
          run:
            - minicpm-v
            # - llama3.2
    pipelines:
      enabled: false
    hostNetwork: true
    resources:
      requests:
        memory: 10Gi
        cpu: 5000m
      limits:
        memory: 15Gi
        cpu: 10000m
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
      - host: openwebui.leonmachado.com
        paths:
        - path: /
          pathType: ImplementationSpecific
    # persistentVolume:
    #   enabled: true
    #   storageClass: longhorn
    #   size: 30Gi
    