---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: victoria-metrics-single
      version: '>=0.13.0 <0.14.0'
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics-charts
        namespace: flux-system
      interval: 5m0s
  values:
    server:
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - name: victoria-metrics.leonmachado.com
            path: /
            pathType: ImplementationSpecific

      persistentVolume:
        enabled: true
        size: 3Gi
