---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: vm/victoria-metrics-cluster
      version: '>=0.11.0 <0.12.0'
      sourceRef:
        kind: HelmRepository
        name: victoria-metrics-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: linuxserver/radarr
      tag: 4.2.4

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - name: victoria-metrics.leonmachado.com
          path: /
          pathType: ImplementationSpecific

    persistentVolume:
      enabled: true
      size: 3Gi
