---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: teamcity
  namespace: flux-system
spec:
  targetNamespace: cicd
  interval: 5m0s
  chart:
    spec:
      chart: teamcity
      version: '0.10.0'
      sourceRef:
        kind: HelmRepository
        name: personal-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: jetbrains/teamcity-server
      tag: 2021.2.3
    ingress:
      enabled: true
      className: public
      hosts:
        - host: teamcity.leonmachado.com
          paths:
            - path: /
              pathType: ImplementationSpecific
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi
