---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://reydelleon.github.io/helm-charts/
      chart: radarr
      version: '>=2.0.0 <3.0.0'
      sourceRef:
        kind: HelmRepository
        name: personal-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: linuxserver/radarr
      tag: 4.2.4

    ingress:
      ingressClassName: nginx
      host: radarr.leonmachado.com
      path: /
      pathType: ImplementationSpecific

    persistence:
      media:
        hostPath: /var/lib/media/plex-library
        size: 500Gi
