---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ollama
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ollama
      version: '>=1.0.0 <2.0.0'
      sourceRef:
        kind: HelmRepository
        name: ollama-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      tag: 0.6.0
    ollama:
      models:
        pull: 
          - minicpm-v
    hostNetwork: true
    resources:
      requests:
        memory: 5g
        cpu: 8000m
      limits:
        memory: 10g
        cpu: 15000m
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
      - host: ollama.leonmachado.com
        paths:
        - path: /
          pathType: ImplementationSpecific
    persistentVolume:
      enabled: true
      storageClass: longhorn
      size: 30Gi
    