---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: '>=8.0.0 <9.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.11.1

    # probes:
    #   startup:
    #     enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: public
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
        - host: frigate.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific
        tls:
          - hosts:
            - frigate.leonmachado.com
            secretName: frigate-tls

    persistence:
      data:
        enabled: true
        storageClass: longhorn
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 5Gi

    configmap:
      config:
        # -- Store frigate configuration as a ConfigMap
        enabled: true

        # -- See [docs](https://blakeblackshear.github.io/frigate/) for more details.
        # @default -- see URL to default config
        data:
          config.yml: |
            mqtt:
              host: mosquitto
              topic_prefix: security/frigate

            detectors:
              cpu1:
                type: cpu
              cpu2:
                type: cpu

            # Defaults section. Some of this can be overwritten in the cameras section.
            detect:
              fps: 5

            record:
              events:
                pre_capture: 5
                post_capture: 5
                retain:
                  default: 5

            snapshots:
              enabled: true
              retain:
                default: 30
            
            objects:
              track:
                - person

            birdseye:
              enabled: True
              width: 1280
              height: 720
              quality: 8
              mode: objects

            cameras:
              back-yard:
                rtmp:
                  enabled: false
                ffmpeg:
                  inputs:
                    # Use the low resolution stream for motion/object detection
                    - path: rtsps://192.168.1.7:7441/YtAp9IVeEihnpIKl?enableSrtp
                      roles:
                        - detect
                    # Use the high resolution stream for recordings
                    - path: rtsps://192.168.1.7:7441/hmI1rZYM7OHjjnfL?enableSrtp
                      roles:
                        - record
                # Prevent any motion detection from being triggered in sky/high areas where people are unlikely to be
                motion:
                  mask: 
                  - 639,196,481,179,265,161,1,152,1,1,640,0
                objects:
                  track:
                    - dog
                detect:
                  enabled: true
                  width: 640
                  height: 360
                record:
                  enabled: true
                  events:
                    objects:
                      - person
                    retain:
                      mode: active_objects

              baby-cam:
                rtmp:
                  enabled: false
                ffmpeg:
                  inputs:
                    # Use the low resolution stream for motion/object detection
                    - path: rtsps://192.168.1.7:7441/MtQxm9taFzfcNO9D?enableSrtp
                      roles:
                        - detect
                    # Use the high resolution stream for recordings
                    - path: rtsps://192.168.1.7:7441/FblhXcraGSXsOdUh?enableSrtp
                      roles:
                        - record
                detect:
                  enabled: true
                  width: 640
                  height: 360
                  stationary:
                    interval: 0
                    threshold: 50
                record:
                  enabled: false
                  events:
                    objects:
                      - person
                    retain:
                      mode: active_objects
