---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: '>=8.0.0 <9.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.10.1-amd64

    # probes:
    #   startup:
    #     enabled: false

    ingress:
      main:
        enabled: true
        ingressClassName: public
        hosts:
        - host: frigate.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific

    # persistence:
    #   data:
    #     enabled: disabled
    #     storageClass: longhorn
    #     mountPath: /data
    #     accessMode: ReadWriteOnce
    #     size: 100Mi

    configmap:
      config:
        # -- Store frigate configuration as a ConfigMap
        enabled: true

        # -- See [docs](https://blakeblackshear.github.io/frigate/) for more details.
        # @default -- see URL to default config
        data:
          config.yml: |
            mqtt:
              host: mosquitto
              topic_prefix: security/frigate
            detectors:
              cpu1:
                type: cpu
              cpu2:
                type: cpu
            cameras:
              backyard:
                ffmpeg:
                  inputs:
                    - path: rtsps://192.168.1.7:7441/YtAp9IVeEihnpIKl?enableSrtp
                      roles:
                        - detect
                detect:
                  width: 640
                  height: 360
        

