---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: '>=8.2.0 <9.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: 0.15.1

    # probes:
    #   startup:
    #     enabled: false

    env:
      PLUS_API_KEY: REDACTED
    
    service:
      main:
        ports:
          rtsp:
            enabled: true
            port: 8554
            targetPort: 8554
            protocol: TCP
          go2rtc:
            enabled: true
            port: 1984
            targetPort: 1984
            protocol: TCP

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
        - host: frigate.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific

    persistence:
      data:
        enabled: true
        storageClass: longhorn
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 5Gi

    configmap:
      config:
        # -- Store frigate configuration as a ConfigMap
        enabled: true

        # -- See [docs](https://blakeblackshear.github.io/frigate/) for more details.
        # @default -- see URL to default config
        data:
          config.yml: |
            mqtt:
              host: mosquitto
              topic_prefix: frigate

            detectors:
              ov_0:
                type: openvino
                device: CPU
              ov_1:
                type: openvino
                device: CPU

            model:
              width: 300
              height: 300
              input_tensor: nhwc
              input_pixel_format: bgr
              path: /openvino-model/ssdlite_mobilenet_v2.xml
              labelmap_path: /openvino-model/coco_91cl_bkgr.txt

            # Defaults section. Some of this can be overwritten in the cameras section.
            detect:
              fps: 5

            record:
              expire_interval: 300 # Do the clean up runs every 5 minutes
              alerts:
                pre_capture: 5
                post_capture: 5
                retain:
                  days: 14
                  mode: active_objects
              detections:
                pre_capture: 5
                post_capture: 5   
                retain:
                  days: 14
                  mode: active_objects            

            snapshots:
              enabled: true
              quality: 80
              retain:
                default: 30

            objects:
              track:
                - person

            audio:
              max_not_heard: 10
              min_volume: 200
              filters:
                rain:
                  threshold: 0.5
                bark:
                  threshold: 0.5
                lawn_mower:
                  threshold: 0.5
                siren:
                  threshold: 0.5
                thunder:
                  threshold: 0.5
                smoke_detector:
                  threshold: 0.5
                glass:
                  threshold: 0.5

            birdseye:
              enabled: true
              width: 1280
              height: 720
              quality: 8
              mode: objects

            go2rtc:
              streams:
                back-yard:
                  - rtspx://192.168.1.2:7441/REDACTED_STREAM_TOKEN # High resolution stream
                back-yard-low:
                  - rtspx://192.168.1.2:7441/REDACTED_STREAM_TOKEN # Low resolution stream
                baby-cam:
                  - rtspx://192.168.1.2:7441/REDACTED_STREAM_TOKEN # High resolution stream
                baby-cam-low:
                  - rtspx://192.168.1.2:7441/REDACTED_STREAM_TOKEN # Low resolution stream
                door-bell:
                  - "ffmpeg:http://192.168.1.42/flv?port=1935&app=bcs&stream=channel0_main.bcs&user=admin&password=ZJd@NCApNiFhrJ99#video=copy#audio=copy#audio=opus"
                  - rtsp://192.168.1.42/Preview_01_sub
                door-bell-low:
                  - "ffmpeg:http://192.168.1.42/flv?port=1935&app=bcs&stream=channel0_ext.bcs&user=admin&password=ZJd@NCApNiFhrJ99"

            cameras:
              back-yard:
                enabled: true
                ffmpeg:
                  output_args:
                    # rtmp: preset-rtmp-ubiquiti # Only use when streaming directly from Ubiquiti DVR
                    # record: preset-record-ubiquiti # Only use when streaming directly from Ubiquiti DVR
                    record: preset-record-generic-audio-copy
                  inputs:
                    # Use the low resolution stream for object/audio detection
                    # - path: rtsps://192.168.1.2:7441/REDACTED_STREAM_TOKEN?enableSrtp # Use to stream directly from Ubiquiti DVR if Frigate fails
                    - path: rtsp://127.0.0.1:8554/back-yard-low
                      input_args: preset-rtsp-restream
                      roles:
                        - audio
                        - detect
                    # Use the high resolution stream for recordings
                    # - path: rtsps://192.168.1.2:7441/REDACTED_STREAM_TOKEN?enableSrtp # Use to stream directly from Ubiquiti DVR if Frigate fails
                    - path: rtsp://127.0.0.1:8554/back-yard
                      input_args: preset-rtsp-restream
                      roles:
                        - record
                # Prevent any motion detection from being triggered in sky/high areas where people are unlikely to be
                motion:
                  mask: 
                  - 640,148,409,144,241,102,0 ,119,1,1,640,0
                objects:
                  track:
                    - dog
                    - person
                  filters:
                    dog:
                      threshold: 0.5
                    person:
                      threshold: 0.7
                detect:
                  enabled: true
                  width: 640
                  height: 360
                record:
                  enabled: true
                audio:
                  enabled: true
                  listen:
                    - lawn_mower
                    - bark
                    - siren
                    - rain
                    - splinter
                    - thunder
                    - fire
                    - car_alarm
                    - smoke_detector

              baby-cam:
                enabled: true
                ffmpeg:
                  output_args:
                    # rtmp: preset-rtmp-ubiquiti # Only use when streaming directly from Ubiquiti DVR
                    # record: preset-record-ubiquiti # Only use when streaming directly from Ubiquiti DVR
                    record: preset-record-generic-audio-copy
                  inputs:
                    # Use the low resolution stream for motion/object detection
                    # - path: rtsps://192.168.1.2:7441/REDACTED_STREAM_TOKEN?enableSrtp # Use to stream directly from Ubiquiti DVR if Frigate fails
                    - path: rtsp://127.0.0.1:8554/baby-cam-low
                      input_args: preset-rtsp-restream
                      roles:
                        - audio
                        - detect
                    # Use the high resolution stream for recordings
                    # - path: rtsps://192.168.1.2:7441/REDACTED_STREAM_TOKEN?enableSrtp # Use to stream directly from Ubiquiti DVR if Frigate fails
                    - path: rtsp://127.0.0.1:8554/back-yard
                      input_args: preset-rtsp-restream
                      roles:
                        - record
                detect:
                  enabled: true
                  width: 640
                  height: 360
                  stationary:
                    interval: 50
                    threshold: 50
                snapshots:
                  enabled: false
                record:
                  enabled: false
                motion:
                  mask:
                  - 375,223,382,165,476,162,550,248,492,316,401,325
                zones:
                  work-station:
                    coordinates: 274,223,281,303,149,307,148,220
                    objects:
                      - person
                audio:
                  enabled: true
                  listen:
                    - crying
                    - smoke_detector
                    - fire
                    - bark
                    - car_alarm
                    - glass
                    - rain
              
              door-bell:
                enabled: true
                ffmpeg:
                  inputs:
                    # Use the low resolution stream for object/audio detection
                    - path: rtsp://127.0.0.1:8554/door-bell-low
                      input_args: preset-stsp-restream
                      roles:
                        - detect
                    # Use the high resolution stream for recordings
                    - path: rtsp://127.0.0.1:8554/door-bell
                      input_args: preset-stsp-restream
                      roles:
                        - record

