---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: '>=8.2.0 <9.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: stable

    # probes:
    #   startup:
    #     enabled: false

    env:
      PLUS_API_KEY: REDACTED

    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
        - host: frigate.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific

    persistence:
      data:
        enabled: true
        storageClass: longhorn
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 5Gi

    configmap:
      config:
        # -- Store frigate configuration as a ConfigMap
        enabled: true

        # -- See [docs](https://blakeblackshear.github.io/frigate/) for more details.
        # @default -- see URL to default config
        data:
          config.yml: |
            mqtt:
              host: mosquitto
              topic_prefix: homeassistant

            detectors:
              cpu1:
                type: cpu
              cpu2:
                type: cpu

            # Defaults section. Some of this can be overwritten in the cameras section.
            detect:
              fps: 5

            record:
              events:
                pre_capture: 5
                post_capture: 5
                retain:
                  default: 5

            snapshots:
              enabled: true
              retain:
                default: 30

            objects:
              track:
                - person

            audio:
              max_not_heard: 10
              min_volume: 200
              filters:
                rain:
                  threshold: 0.5
                bark:
                  threshold: 0.5
                lawn_mower:
                  threshold: 0.5
                siren:
                  threshold: 0.5
                thunder:
                  threshold: 0.5
                fire_alarm:
                  threshold: 0.5
                glass:
                  threshold: 0.5

            birdseye:
              enabled: True
              width: 1280
              height: 720
              quality: 8
              mode: objects

            go2rtc:
              streams:
                back-yard:
                  - rtspx://192.168.1.2:7441/REDACTED_STREAM_TOKEN # High resolution stream
                back-yard-low:
                  - rtspx://192.168.1.2:7441/REDACTED_STREAM_TOKEN # Low resolution stream
                baby-cam:
                  - rtspx://192.168.1.2:7441/REDACTED_STREAM_TOKEN # High resolution stream
                baby-cam-low:
                  - rtspx://192.168.1.2:7441/REDACTED_STREAM_TOKEN # Low resolution stream

            cameras:
              back-yard:
                ffmpeg:
                  output_args:
                    # rtmp: preset-rtmp-ubiquiti # Only use when streaming directly from Ubiquiti DVR
                    # record: preset-record-ubiquiti # Only use when streaming directly from Ubiquiti DVR
                    record: preset-record-generic-audio-copy
                  inputs:
                    # Use the low resolution stream for object/audio detection
                    # - path: rtsps://192.168.1.2:7441/REDACTED_STREAM_TOKEN?enableSrtp # Use to stream directly from Ubiquiti DVR if Frigate fails
                    - path: rtsp://127.0.0.1:8554/back-yard-low
                      input_args: preset-rtsp-restream
                      roles:
                        - audio
                        - detect
                    # Use the high resolution stream for recordings
                    # - path: rtsps://192.168.1.2:7441/REDACTED_STREAM_TOKEN?enableSrtp # Use to stream directly from Ubiquiti DVR if Frigate fails
                    - path: rtsp://127.0.0.1:8554/back-yard
                      input_args: preset-rtsp-restream
                      roles:
                        - record
                # Prevent any motion detection from being triggered in sky/high areas where people are unlikely to be
                motion:
                  mask: 
                  - 639,196,481,179,265,161,1,152,1,1,640,0
                objects:
                  track:
                    - dog
                    - person
                  filters:
                    dog:
                      threshold: 0.5
                detect:
                  enabled: true
                  width: 640
                  height: 360
                record:
                  enabled: true
                  events:
                    objects:
                      - person
                    retain:
                      mode: active_objects
                audio:
                  enabled: true
                  listen:
                    - lawn_mower
                    - bark
                    - siren
                    - rain
                    - splinter
                    - thunder
                    - fire
                    - fire_alarm

              baby-cam:
                ffmpeg:
                  output_args:
                    # rtmp: preset-rtmp-ubiquiti # Only use when streaming directly from Ubiquiti DVR
                    # record: preset-record-ubiquiti # Only use when streaming directly from Ubiquiti DVR
                    record: preset-record-generic-audio-copy
                  inputs:
                    # Use the low resolution stream for motion/object detection
                    # - path: rtsps://192.168.1.2:7441/REDACTED_STREAM_TOKEN?enableSrtp # Use to stream directly from Ubiquiti DVR if Frigate fails
                    - path: rtsp://127.0.0.1:8554/baby-cam-low
                      input_args: preset-rtsp-restream
                      roles:
                        - audio
                        - detect
                    # Use the high resolution stream for recordings
                    # - path: rtsps://192.168.1.2:7441/REDACTED_STREAM_TOKEN?enableSrtp # Use to stream directly from Ubiquiti DVR if Frigate fails
                    - path: rtsp://127.0.0.1:8554/back-yard
                      input_args: preset-rtsp-restream
                      roles:
                        - record
                detect:
                  enabled: true
                  width: 640
                  height: 360
                  stationary:
                    interval: 50
                    threshold: 50
                snapshots:
                  enabled: false
                record:
                  enabled: false
                  events:
                    objects:
                      - person
                    retain:
                      mode: active_objects
                zones:
                  work-station:
                    coordinates: 274,223,281,303,149,307,148,220
                    objects:
                      - person
                audio:
                  enabled: true
                  listen:
                    - crying
                    - fire_alarm
                    - fire
                    - bark
                    - car_alarm
                    - glass
                    - rain
