---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: frigate
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: frigate
      version: '>=6.1.0 <7.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: blakeblackshear/frigate
      tag: 0.8.0-amd64

    ingress:
      main:
        enabled: true
        ingressClassName: public
        hosts:
        - host: frigate.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific

    persistence:
      data:
        enabled: true
        storageClass: longhorn
        mountPath: /data
        accessMode: ReadWriteOnce
        size: 100Mi
    
    config: |
      mqtt:
        host: mqtt.leonmachado.com
        topic_prefix: security/detection
      database:
        path: /data/frigate.db
      
