---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: influxdb2
      version: '>=2.0.0 <3.0.0'
      sourceRef:
        kind: HelmRepository
        name: influx-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: influxdb
      tag: 2.3.0-alpine
    adminUser:
      organization: "little-lodge"
      bucket: "default"
      user: "admin"
      retention_policy: "0s"
      ## Leave empty to generate a random password and token.
      ## Or fill any of these values to use fixed values.
      password: ""
      token: ""
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
      path: /
      hostname: influx.leonmachado.com
      tls:
        - hosts:
          - influx.leonmachado.com
          secretName: influx-tls
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 2Gi
