---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elasticsearch
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 5m0s
  chart:
    spec:
      chart: elasticsearch
      version: 8.5.1
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 5m0s
  values:
    sysctlInitContainer:
      enabled: false
    esConfig:
      elasticsearch.yml: |
        node.store.allow_mmap: false
    antiAffinity: "soft"
    esJavaOpts: "-Xmx128m -Xms128m"
    resources:
      requests:
        cpu: "100m"
        memory: "512M"
      limits:
        cpu: "1000m"
        memory: "512M"
    volumeClaimTemplate:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn"
      resources:
        requests:
          storage: 500M
    ingress:
      enabled: true
      className: public
      hosts:
        - host: elastic.leonmachado.com
          paths:
            - path: /
      tls:
        - secretName: elasticsearch-tls
          hosts:
            - elastic.leonmachado.com
