---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kibana
  namespace: flux-system
spec:
  targetNamespace: monitoring
  interval: 5m0s
  chart:
    spec:
      chart: elastic/kibana
      version: '7.17.3'
      sourceRef:
        kind: HelmRepository
        name: elastic-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image: docker.elastic.co/kibana/kibana
    imageTag: 7.17.3
    
    ingress:
      enabled: true
      className: public
      path: /
      pathType: ImplementationSpecific
      hosts:
        - host: kibana.leonmachado.com
          paths:
            - path: /

