---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-bridge
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: homebridge
      version: '>=5.0.0 <6.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: homebridge/homebridge
      tag: "2025-09-03"
    env:
      TZ: "America/New_York"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
        - host: homebridge.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 1Gi