---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ingress-nginx
      version: '>=4.00 <5.0.0'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m0s
  values:
    controller:
      service:
        annotations: {}   # remove deprecated metallb.universe.tf/ip-allocated-from-pool