---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m0s
  chart:
    spec:
      chart: cert-manager
      version: '>=1.0.0 <2.0.0'
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      interval: 5m0s
  values:
    installCRDs: true
    # extraArgs:
    #   - --dns01-recursive-nameservers-only
    #   - --dns01-recursive-nameservers=10.152.183.10:53
