---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: metallb
      version: '>=0.0.0 <20.0.0'
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m0s
  values:
    speaker:
    frr:
      enabled: false
