---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://reydelleon.github.io/helm-charts/
      chart: sonarr
      version: '>=3.0.0 <4.0.0'
      sourceRef:
        kind: HelmRepository
        name: personal-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: linuxserver/sonarr
      tag: 4.0.9

    ingress:
      ingressClassName: nginx
      host: sonarr.leonmachado.com
      path: /
      pathType: ImplementationSpecific

    persistence:
      media:
        hostPath: /var/lib/media/plex-library
        size: 500Gi
