---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: longhorn
      version: 1.8.0 # Pinning chart version to use it as the upgrading hook
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m0s
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      host: longhorn.leonmachado.com
      path: /
      pathType: ImplementationSpecific
    csi:
      kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet # This is necessary to address an issue causing the CSI driver to fail
    persistence:
      defaultClassReplicaCount: 1
      reclaimPolicy: Retain
    defaultSettings:
      storageOverProvisioningPercentage: 200
      storageMinimalAvailablePercentage: 5
      defaultReplicaCount: 1
      defaultDataPath: /var/lib/longhorn/
      