---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: longhorn
      version: '>=1.0.0 <2.0.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m0s
  values:
    ingress:
      enabled: true
      ingressClassName: public
      host: longhorn.leonmachado.com
      path: /
      pathType: ImplementationSpecific
    csi:
      kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet # This is necessary to address an issue causing the CSI driver to fail
    defaultSettings:
      storageOverProvisioningPercentage: 200
      storageMinimalAvailablePercentage: 5
      defaultReplicaCount: 3
      defaultDataPath: /var/lib/longhorn/
      