---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: longhorn/longhorn
      version: '>=1.0.0 <2.0.0'
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m0s
  values:
    ingress:
      enable: true
      ingressClassName: public
      host: longhorn.leonmachado.com
      path: /
      pathType: ImplementationSpecific
