---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: personal-charts
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://reydelleon.github.io/helm-charts/

