---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nzbget
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: nzbget
      version: '>=3.0.0 <4.0.0'
      sourceRef:
        kind: HelmRepository
        name: personal-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: linuxserver/nzbget
      tag: version-v21.1

    ingress:
      ingressClassName: public
      host: nzbget.leonmachado.com
      path: /
      pathType: ImplementationSpecific

    persistence:
      downloads:
        storageClassName: manual
        hostPath: /var/lib/media/plex-library/Downloads
        mountPath: /media/Downloads
        size: 500Gi
