---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: grafana
      version: '>=6.15.0 <7.0.0'
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: grafana/grafana
      tag: 9.2.6
      namespaceOverride: monitoring
    ingress:
      enabled: true
      ingressClassName: public
      annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
      path: /
      pathType: ImplementationSpecific
      hosts:
        - monitoring.leonmachado.com
      tls:
        - hosts:
          - monitoring.leonmachado.com
          secretName: grafana-tls
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi
    admin:
      existingSecret: grafana-credentials
      userKey: admin-user
      passwordKey: admin-password
    sidecar:
      datasources:
        enabled: true
        label: grafana-datasource
        resource: secret
