---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  interval: 5m0s
  chart:
    spec:
      chart: grafana
      varsion: '<=6.15.0 <7.0.0'
      sourceRef:
        kind: HelmRepository
        name: stable
      interval: 5m0s
  values:
    image:
      repository: grafana/grafana
      tag: 8.1.1
    ingress:
      enabled: true
      ingressClassName: public
      path: /
      pathType: ImplementationSpecific
      hosts:
        - grafana.leonmachado.com
    persistence:
      enabled: true
      storageClassName: longhorn
      size: 5Gi
    admin:
      existingSecret: grafana-credentials
      userKey: admin-user
      passwordKey: admin-password


