---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: home-assistant
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2021.8.5
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: public
        hosts:
        - host: home-assistant.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
      
    add-ons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 3.11.1
        workingDir: /config
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          ingressClassName: public
          hosts:
          - host: home-assistant-config.leonmachado.com
            paths:
            - path: /
              pathType: ImplementationSpecific
          volumeMounts:
          - name: config
            mountPath: /config
