---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: home-assistant
      version: '>=13.0.0 <14.0.0'
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m0s
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2022.5.1
    env:
      TZ: "America/New_York"
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    ingress:
      main:
        enabled: true
        ingressClassName: public
        hosts:
        - host: home-assistant.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific
    persistence:
      config:
        enabled: true
        storageClass: longhorn
        size: 5Gi
    addons:
      codeserver:
        enabled: true
        env:
          TZ: "America/New_York"
        image:
          repository: codercom/code-server
          tag: 4.3.0
        workingDir: /config
        args:
          - --user-data-dir
          - "/config/.vscode"
          - --auth
          - "none"
        ingress:
          enabled: true
          ingressClassName: public
          hosts:
          - host: home-assistant-config.leonmachado.com
            paths:
            - path: /
              pathType: ImplementationSpecific
        volumeMounts:
        - name: config
          mountPath: /config
