---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: home-assistant
      version: 9.3.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  install: {}
  values:
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: public
        hosts:
        - host: home-assistant.leonmachado.com
          paths:
          - path: /
            pathType: ImplementationSpecific

